2018-01-09 21:06:42,022 ERROR    /home/suyue/opsweb/api/views.py[line:228] tomcat日志获取失败ConnectionError((<urllib3.connection.HTTPConnection object at 0x7f6ac02e4080>, 'Connection to 121.41.23.54 timed out. (connect timeout=30)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7f6ac02e4080>, 'Connection to 121.41.23.54 timed out. (connect timeout=30)'))
